# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
